version: "3"

services:
  leaky-app:
    container_name: memoria-leak
    build: ./leaky-app
    mem_limit: 1g
    ports:
      - "3001:3000"
    command: node index.js

  clean-app:
    container_name: memoria-clean
    build: ./clean-app
    mem_limit: 1g
    ports:
      - "3002:3000"
    command: node index.js
